language: bash
sudo: required
dist: trusty
before_script:
- sudo apt-get update -q
- sudo pip install ansible==2.0.2.0
- sudo modprobe overlayfs
script:
#- sudo ./build_all.sh
- sudo mkdir -p /tmp/on-imagebuilder/builds/
- sudo mkdir -p /tmp/on-imagebuilder/ipxe/
- sudo mkdir -p /tmp/on-imagebuilder/syslinux/
- sudo touch /tmp/on-imagebuilder/builds/builds.txt
- sudo touch /tmp/on-imagebuilder/ipxe/ipxe.txt
- sudo touch /tmp/on-imagebuilder/syslinux/syslinux.txt

before_deploy:
- sudo chmod 644 /tmp/on-imagebuilder/builds/*
- sudo chmod 644 /tmp/on-imagebuilder/ipxe/*
- sudo chmod 644 /tmp/on-imagebuilder/syslinux/*
- gen_bintray_cfg.bash "${TRAVIS_BRANCH}"
deploy:
  provider: bintray
  file: .bintray.json
  user: $BINTRAY_USER
  key: $BINTRAY_KEY
  on:
    all_branches: true


